### ISSUE TITLE
extract video stream from html to c++

### ISSUE THREAD

**Issue by utsavrai** [nadjieb/cpp-mjpeg-streamer#19]
Is there any way of extracting real-time HTML video to c++ environment, suppose I have webrtc media which I want to process frame by frame at high-resolution 30fps but the conversion of every frame to base64 using javascript is very computationally expensive and causes too much delay.

**Comment by kamalnadjieb** [comment]
Hi, sorry for late reply.

If you browse on the internet, there are several WebRTC client libraries in C++. You can also create an intermediary NodeJS client that receives WebRTC stream from web browser then forward it to another C++ process using an interprocess cross-language communication library (there must be one). To reduce the latency, I think you don't have any choice but to reduce the quality and resolution of the frames or using transport protocol other than TCP.

FYI, I built this library to help scientists and hobbyists to visualize their project and not focusing on perfomance (at least for now). Since this library is using HTTP (which is built on top of TCP that has handshakes and congestion control), of course it is less performance if you compare it to another library that using other protocol like UDP.

Thank you.
